[profile.default]
optimizer = true
optimizer_runs = 10000
gas_reports = ["Multipool", "MultipoolRouter"]
fs_permissions = [{ access = "read-write", path = "./test/snapshots/"}]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "oz-proxy/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "prb-math/=lib/prb-math/src/",
    "uniswapv3/=lib/v3-core/contracts/",
]
build_info = true
extra_output = ["storageLayout"]
solc_version = "0.8.19"

[profile.ci]
verbosity = 4

[invariant]
#fail_on_revert = true

[fmt]
int_types = "preserve"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ETHERSCAN_KEY}" }
