[profile.default]
optimizer = true
optimizer_runs = 20_000

[profile.ci]
verbosity = 4

[invariant]
fail_on_revert = true

[fmt]
int_types = "preserve"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ETHERSCAN_KEY}" }
