[profile.default]
optimizer = true
optimizer_runs = 500
gas_reports = ["Multipool", "MultipoolRouter", "Trader", "ContextMath"]
fs_permissions = [{ access = "read-write", path = "./test/snapshots/"}]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "oz-proxy/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "uniswapv3/=lib/v3-core/contracts/",
    "uniswapv3-router/=lib/v3-periphery/contracts/",
]
bytecode_hash = 'none'
solc_version = "0.8.19"

[profile.ci]
verbosity = 4

[fmt]
int_types = "preserve"
line_length = 100
wrap_comments = true
multiline_func_header = "all"
override_spacing = false

[invariant]
fail_on_revert = false


# Dependencies 
#[submodule "lib/forge-std"]
#	path = lib/forge-std
#	url = https://github.com/foundry-rs/forge-std
#    tag = v1.8.0
#[submodule "lib/v3-core"]
#	path = lib/v3-core
#	url = https://github.com/uniswap/v3-core
#    tag = v1.0.0
#[submodule "lib/openzeppelin-contracts-upgradeable"]
#	path = lib/openzeppelin-contracts-upgradeable
#    url = https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable
#    tag = v4.9.3
#[submodule "lib/openzeppelin-contracts"]
#	path = lib/openzeppelin-contracts
#	url = https://github.com/OpenZeppelin/openzeppelin-contracts
#    tag = v4.9.3
#[submodule "lib/v3-periphery"]
#	path = lib/v3-periphery
#	url = https://github.com/uniswap/v3-periphery
#    tag = v1.3.0
